import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Lobster } from "next/font/google";
import Sidebar from "./components/sideBar";
import Header from "./components/header";
import MobileNav from "./components/mobileNav";

const lobster = Lobster({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={` ${geistMono.variable} antialiased`}
        style={{ fontFamily: "Yekan, sans-serif" }}
      >
        <Header />
        <div className="flex">
          <aside className="block [@media(max-width:790px)]:hidden w-[72px] xl:min-w-[244px] border-l border-l-gray-300 h-auto px-3 pb-5 pt-2">
            <div className="w-full h-full">
              <Sidebar />
            </div>
          </aside>
          <main className="flex-1 w-full">{children}</main>
        </div>
        <div className="mx-auto">
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
